##############################
# Headless Service
##############################
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solution-ui
  name: solution-ui-service-headless
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: slt-ui
      protocol: TCP
  selector:
    app: solution-ui
