apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution-ui-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  # spec.selector.matchLabels : 각 overlays 에서 overriding
  selector:
    matchLabels:
      app: solution-ui
  template:
    # spec.template.metadata.labels : 각 overlays 에서 overriding
    metadata:
      labels:
        app: solution-ui
    spec:
      imagePullSecrets:
        - name: private-image-registry
      containers:
        - name: solution-ui-container
          image: lgu-did/solution-ui
          imagePullPolicy: IfNotPresent
          ports:
            - name: slt-ui
              containerPort: 8080   # ubi8/httpd-24 HTTP port
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # spec.template.spec.containers.name.resources : 각 overlays 에서 overriding
          resources:
            limits:
              memory: "336Mi"
              cpu: "0.3"
