apiVersion: v1
kind: Secret
metadata:
  name: micm-dev-postgresql-secret
  namespace: dmicma
type: Opaque
data:
  ### Solution Postgresql ::: START

  # [ Postgresql VM 전환시 삭제 예정 ]
  # Solution PostgreSQL 의 'postgres' 계정 Password
  # value : 'solution'
  solution-postgres-password: "c29sdXRpb24K"

  # Solution PostgreSQL 의 일반 계정 Password
  # value : 'solution-01-1234'
  solution-user-password: "c29sdXRpb24tMDEtMTIzNA=="

  ### Solution Postgresql ::: END

  ##############################

  ### Service Postgresql ::: START

  # [ Postgresql VM 전환시 삭제 예정 ]
  # Service PostgreSQL 의 'postgres' 계정 Password
  # value : 'service'
  service-postgres-password: "c2VydmljZQ=="

  # Service PostgreSQL 의 일반 계정 Password
  # value : 'service-01-1234'
  service-user-password: "c2VydmljZS0wMS0xMjM0"

  ### Service Postgresql ::: END

  ##############################

  ### Acapy Postgresql ::: START

  # {
  #   "account":"solution-01",
  #   "password":"solution-01-1234",
  #   "admin_account":"solution-01",
  #   "admin_password":"solution-01-1234"
  # }
  ACAPY_WALLET_STORAGE_CREDS: |+   # wallet 저장소 접근에 필요한 인증 정보
    ewogICJhY2NvdW50Ijoic29sdXRpb24tMDEiLAogICJwYXNzd29yZCI6InNvbHV0aW9uLTAxLTEy
    MzQiLAogICJhZG1pbl9hY2NvdW50Ijoic29sdXRpb24tMDEiLAogICJhZG1pbl9wYXNzd29yZCI6
    InNvbHV0aW9uLTAxLTEyMzQiCn0K

  ### Acapy Postgresql ::: END
