apiVersion: apps/v1
kind: StatefulSet
metadata:
  # 'monachain-indy-node' 로 고정해야 함 : monachain-indy-node-0 ~ monachain-indy-node-3 까지 Pod 명 fix
  name: monachain-indy-node
spec:
  serviceName: indy-node
  # 해당 replicas 값은 의미 없음 : 각 overlays 에서 항상 4 로 overriding
  replicas: 4
  revisionHistoryLimit: 3
  # spec.selector.matchLabels : 각 overlays 에서 필요시 overriding
  selector:
    matchLabels:
      app: indy-node
  template:
    # spec.template.metadata.labels : 각 overlays 에서 필요시 overriding
    metadata:
      labels:
        app: indy-node
    spec:
      ### 추후 Harbor 연동 secret 으로 변경 예정
      # imagePullSecrets:
      #  - name: private-image-registry
      containers:
        - name: indy-node-container
          image: harbor-core.lguplus-registry.svc.cluster.local/micm-dev/uplus-indy-node
          imagePullPolicy: IfNotPresent
          ports:
            - name: node-port
              containerPort: 9701   # 9701 : Indy Node 내부 통신 Port
            - name: client-port
              containerPort: 9702   # 9702 : Indy Node 외부 통신 Port
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: UID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          # spec.template.spec.containers.name.resources : 각 overlays 에서 필요시 overriding
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
