apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app: solution-registry
images:
- name: lgu-did/solution-registry
  newName: nexus.example.com:5000/dmicma/solution-registry-dev
  newTag: 20230821-074432
generatorOptions:
  disableNameSuffixHash: true
replicas:
- count: 1
  name: solution-registry-deployment
resources:
- ../../base
- service-dev.yaml
patches:
- path: deployment-dev.yaml
