apiVersion: v1
kind: Secret
metadata:
  name: micm-postgresql-secret-dev
  namespace: dmicma    # 개발 환경 namespace
type: Opaque
data:
  ### Solution Postgresql ::: START

  # Solution PostgreSQL 의 일반 계정 Password
  # value : 'solution_01_1234'
  solution-user-password: "c29sdXRpb25fMDFfMTIzNA=="

  ### Solution Postgresql ::: END

  ##############################

  ### Service Postgresql ::: START

  # Service PostgreSQL 의 일반 계정 Password
  # value : 'service_01_1234'
  service-user-password: "c2VydmljZV8wMV8xMjM0"

  ### Service Postgresql ::: END

  ##############################

  ### Acapy Postgresql ::: START

  # {
  #   "account":"solution_01",
  #   "password":"solution_01_1234",
  #   "admin_account":"acapy_01",
  #   "admin_password":"acapy_01_1234"
  # }
  ACAPY_WALLET_STORAGE_CREDS: |+   # wallet 저장소 접근에 필요한 인증 정보
    ewogICJhY2NvdW50Ijoic29sdXRpb25fMDEiLAogICJwYXNzd29yZCI6InNvbHV0aW9uXzAxXzEyMzQiLAogICJhZG1pbl9hY2NvdW50IjoiYWNhcHlfMDEiLAogICJhZG1pbl9wYXNzd29yZCI6ImFjYXB5XzAxXzEyMzQiCn0=

  ### Acapy Postgresql ::: END
