apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app: solution-ui
images:
- name: lgu-did/solution-ui
  newName: nexus.example.com:5000/dmicma/solution-ui-dev
  newTag: 20230816-091606
generatorOptions:
  disableNameSuffixHash: true
replicas:
- count: 1
  name: solution-ui-deployment
resources:
- ../../base
- service-dev.yaml
patches:
- path: deployment-dev.yaml
