apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app: indy-node
images:
- name: harbor-core.lguplus-registry.svc.cluster.local/micm-dev/uplus-indy-node
  # 개발 환경 image url 로 override : base 에 지정된 image url 과 동일
  newName: harbor-core.lguplus-registry.svc.cluster.local/micm-dev/uplus-indy-node
  newTag: 1.0.0
generatorOptions:
  disableNameSuffixHash: false
replicas:
# indy-node 의 replicas 개수는 반드시 4 로 고정 필요
- count: 4
  name: monachain-indy-node
resources:
- ../../base
- configmap.yaml
- service.yaml
- script.yaml
patches:
- path: statefulset.yaml
