##############################
# NodePort Service
##############################
apiVersion: v1
kind: Service
metadata:
  labels:
    app: indy-node
  name: indy-node-0-service-nodeport
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - port: 9702
      targetPort: client-port   # 9702 : Indy Node 외부 통신 Port
      nodePort: 30007
      protocol: TCP
  selector:
    app: indy-node
    statefulset.kubernetes.io/pod-name: monachain-indy-node-0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: indy-node
  name: indy-node-1-service-nodeport
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - port: 9702
      targetPort: client-port   # 9702 : Indy Node 외부 통신 Port
      nodePort: 30008
      protocol: TCP
  selector:
    app: indy-node
    statefulset.kubernetes.io/pod-name: monachain-indy-node-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: indy-node
  name: indy-node-2-service-nodeport
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - port: 9702
      targetPort: client-port   # 9702 : Indy Node 외부 통신 Port
      nodePort: 30009
      protocol: TCP
  selector:
    app: indy-node
    statefulset.kubernetes.io/pod-name: monachain-indy-node-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: indy-node
  name: indy-node-3-service-nodeport
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - port: 9702
      targetPort: client-port   # 9702 : Indy Node 외부 통신 Port
      nodePort: 30010
      protocol: TCP
  selector:
    app: indy-node
    statefulset.kubernetes.io/pod-name: monachain-indy-node-3
