apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app: acapy-agency
images:
- name: lgu-did/acapy-agency
  newName: nexus.example.com:5000/dmicma/acapy-agency-loc
  newTag: 0.7.5-custom
generatorOptions:
  disableNameSuffixHash: true
replicas:
- count: 1
  name: acapy-agency-deployment
resources:
- ../../base
- configmap-dev.yaml
- service-dev.yaml
patches:
- path: deployment-dev.yaml
