apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app: acapy-agency
images:
- name: harbor-core.lguplus-registry.svc.cluster.local/micm-dev/uplus-acapy
  newTag: 0.7.5
generatorOptions:
  disableNameSuffixHash: false
replicas:
- count: 1
  name: acapy-agency-deployment
resources:
- ../../base
- configmap.yaml
- route.yaml
- script.yaml
patches:
- path: deployment.yaml
