##############################
# Headless Service
##############################
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-backend
  name: service-backend-service-headless
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: svc-bkd
      protocol: TCP
  selector:
    app: service-backend
